### ISSUE TITLE
tsc:check:tests has been failing on master since #584: private field access in forward-expiry-catchup-jump.test.ts

### ISSUE THREAD

**Issue by coreyphillips** [coreyphillips/beignet#607]
`npm run tsc:check:tests` fails on master and has since `fbba9db` (#584). Nine consecutive master
commits are red.

```
tests/lightning/forward-expiry-catchup-jump.test.ts(212,11): error TS2341: Property '_state' is private and only accessible within class 'ChainMonitor'.
tests/lightning/forward-expiry-catchup-jump.test.ts(213,11): error TS2341: Property '_trackedOutputs' is private and only accessible within class 'ChainMonitor'.
```

## History

| commit | type-check |
|---|---|
| `70c3146` | success |
| `afda963` | success |
| `e0660b9` | success |
| **`fbba9db`** (#584) | **failure** |
| `282d74e`, `0cc6c25`, `2c869cf`, `b895957`, `8479724`, `2e38a8d`, `09faf0c`, `e1e7118` | failure |

## Cause

`tests/lightning/forward-expiry-catchup-jump.test.ts:212-213` assigns to two private fields
without a cast:

```ts
monitor._state = MonitorState.RESOLVING;
monitor._trackedOutputs = [
```

The rest of the suite already has a convention for this. `tests/lightning/chain-monitor.test.ts`
casts at every such site, for example `:1966`, `:2031`, `:2089`, `:2116`, `:2124`:

```ts
(monitor as any)._trackedOutputs = [
```

## Why it was not caught

`tsconfig.json` sets `"ts-node": { "transpileOnly": true }` (from #390 / PR #395), so mocha does
not type-check and `npm run test:lightning` is green on this file. Type safety was deliberately
moved to the separate `type-check.yml` workflow, and that is exactly the gate that is red. The
tsconfig comment says as much:

> Types are not lost: type-check.yml runs tsc:check and tsc:check:tests on the same events

`tsc:check` (src only) still passes; it is only `tsc:check:tests` that fails.

## Fix

Add the cast on both lines, matching `chain-monitor.test.ts`. Two characters of change per line,
no behaviour change.

## Worth considering separately

A red gate that nobody notices for nine commits is the real problem here. `type-check.yml` runs on
`pull_request` and on `push` to master, so the signal exists and was not acted on. Options: make
the check required for merge, or fold `tsc:check:tests` into a step of the `tests` job so a red
type check blocks the same job the unit tests do.
